# Introduction to Numpy for Machine Learning
This will not be an extensive introduction. Just enough to get you started so you can use it for Machine Learning

## Numpy Arrays

In [1]:
# We always import Numpy as follows in order not to pollute the namespace
import numpy as np

In [2]:
# central to Numpy is a special array type 
# to create it we pass a Python list
v = np.array([2,6,4,3])

In [3]:
print(v)

[2 6 4 3]


In [4]:
v.shape

(4,)

In [5]:
# We can also pass in a 2 dimensional Python list to create a 2D array
m = np.array([[1, 2, 5], [4, 3, 4],[5,2,5]])
print(m)

[[1 2 5]
 [4 3 4]
 [5 2 5]]


In [6]:
type(m) 

numpy.ndarray

In [7]:
m.shape

(3, 3)

In [8]:
# Accessing is same as in Python arrays
m[1][2]

4

In [9]:
# But we can ALSO access the elements using a shorter notation
m[1,2]

4

In [10]:
m2 = np.zeros((3,4))

In [11]:
print(m2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
m3 = np.ones((3,4))

In [13]:
print(m3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Matrix Calculations

In [15]:
print(m)

[[1 2 5]
 [4 3 4]
 [5 2 5]]


In [16]:
# Transpose of a matrix is when columns and rows are swapped
print(m.T)

[[1 4 5]
 [2 3 2]
 [5 4 5]]


In [17]:
# Matrix multiplication m x m
m.dot(m.T)

array([[30, 30, 34],
       [30, 41, 46],
       [34, 46, 54]])

In [18]:
m

array([[1, 2, 5],
       [4, 3, 4],
       [5, 2, 5]])

In [19]:
m.sum()/12

2.5833333333333335

In [20]:
# Average
m.mean()

3.4444444444444446

In [21]:
# Variance
m.var()

2.0246913580246915

In [22]:
# Calculate matrix inverse 
inv = np.linalg.inv(m)

In [23]:
print(inv)

[[-2.50000000e-01  0.00000000e+00  2.50000000e-01]
 [ 6.93889390e-17  7.14285714e-01 -5.71428571e-01]
 [ 2.50000000e-01 -2.85714286e-01  1.78571429e-01]]


In [24]:
# Check that this gives the identity when multiplied 
inv.dot(m)

array([[ 1.00000000e+00, -1.11022302e-16, -2.77555756e-16],
       [-2.22044605e-16,  1.00000000e+00,  2.22044605e-16],
       [ 2.22044605e-16,  5.55111512e-17,  1.00000000e+00]])

## Vectorized Calculations

In [25]:
print(m)

[[1 2 5]
 [4 3 4]
 [5 2 5]]


In [26]:
import math 

In [27]:
np.exp(m)

array([[  2.71828183,   7.3890561 , 148.4131591 ],
       [ 54.59815003,  20.08553692,  54.59815003],
       [148.4131591 ,   7.3890561 , 148.4131591 ]])

In [28]:
# By invoking the corresponding numpy function we can do fast vectorized calculations
np.exp(m)

array([[  2.71828183,   7.3890561 , 148.4131591 ],
       [ 54.59815003,  20.08553692,  54.59815003],
       [148.4131591 ,   7.3890561 , 148.4131591 ]])

In [29]:
m.ndim

2

In [30]:
len(m)

3